### ISSUE TITLE
[Bug] Display modal on Tablet and Phone device not working

### ISSUE THREAD

**Issue by Nycolaide** [minedelve/manakit#35]
All content in Modal not display in modal for Phone and Tablet. 

In inspect element webbrowser PC not reproduce Bug.

Only in mobile device.

**Comment by Nycolaide** [comment]
```scss 
	.modal-container {
		// display: flex;

		// background-color: #ff000033;
		// border: 1px solid yellow;
		// width: 100%;
		// height: 100%;
		// justify-content: center;
		// max-height: calc(100% - 3rem);
		transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
		transition-timing-function: cubic-bezier(0, 0, 0.2, 1);
		transition-duration: 0.2s;

		& > * {
			margin: 0 auto;
		}
	}

```
