### ISSUE TITLE
Bug class css not support x.x format ! 

### ISSUE THREAD

**Issue by Nycolaide** [minedelve/manakit#7]
### List format class CSS create by manakit Core

- .y:x-z
- .x
- .x-z
- .x-z.v
- .y:x-z.v

Error in generated app.css 
`{ expectedcss(css-lcurlyexpected)`

for example 
```css
.px-2.5 {
  padding-left: 0.625rem !important;
  padding-right: 0.625rem !important;
}
```
